### ISSUE TITLE
Differences between configuration files

### ISSUE THREAD

**Issue by marcalwestf** [erpya/adempiere-ui-gateway#66]
Both files .env and env_template.env  differ in the definition of KAFKA_PORT:

File env_template.env:
![Selection_001](https://github.com/adempiere/adempiere-ui-gateway/assets/1789408/4863ee71-4347-4339-8529-889cb9b0f5fa)

File .env:
![Selection_002](https://github.com/adempiere/adempiere-ui-gateway/assets/1789408/32252c17-c05c-47e3-a400-cfa2a6dbc2ed)

It seems the definition of env_template.env is more correct.

**Comment by EdwinBetanc0urt** [comment]
Both definitions are now the same

![image](https://github.com/adempiere/adempiere-ui-gateway/assets/20288327/f375b8b6-40d9-44cb-9d9e-a04b87388bfe)

![image](https://github.com/adempiere/adempiere-ui-gateway/assets/20288327/0f18976c-6826-4a5f-8119-db0a16e11397)
